In [1]:
import pandas as pd
#讀取CSV檔案
data = pd.read_csv('mushrooms.csv')

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   type                    8124 non-null   object
 1   cap_shape               8124 non-null   object
 2   cap_surface             8124 non-null   object
 3   cap_color               8124 non-null   object
 4   odor                    8124 non-null   object
 5   stalk_shape             8124 non-null   object
 6   stalk_color_above_ring  8124 non-null   object
 7   stalk_color_below_ring  8124 non-null   object
 8   ring_number             8124 non-null   object
 9   ring_type               8124 non-null   object
 10  population              8124 non-null   object
 11  habitat                 8124 non-null   object
dtypes: object(12)
memory usage: 761.8+ KB


In [15]:
data

type cap_shape cap_surface cap_color odor stalk_shape  \
0       p         x           s         n    p           e   
1       e         x           s         y    a           e   
2       e         b           s         w    l           e   
3       p         x           y         w    p           e   
4       e         x           s         g    n           t   
...   ...       ...         ...       ...  ...         ...   
8119    e         k           s         n    n           e   
8120    e         x           s         n    n           e   
8121    e         f           s         n    n           e   
8122    p         k           y         n    y           t   
8123    e         x           s         n    n           e   

     stalk_color_above_ring stalk_color_below_ring ring_number ring_type  \
0                         w                      w           o         p   
1                         w                      w           o         p   
2                         w                      w           o         p   
3                         w                      w           o         p   
4                         w                      w           o         e   
...                     ...                    ...         ...       ...   
8119                      o                      o           o         p   
8120                      o                      o           o         p   
8121                      o                      o           o         p   
8122                      w                      w           o         e   
8123                      o                      o           o         p   

     population habitat  
0             s       u  
1             n       g  
2             n       m  
3             s       u  
4             a       g  
...         ...     ...  
8119          c       l  
8120          v       l  
8121          c       l  
8122          v       l  
8123          c       l  

[8124 rows x 12 columns]

In [4]:
data.describe()

type cap_shape cap_surface cap_color  odor stalk_shape  \
count   8124      8124        8124      8124  8124        8124   
unique     2         6           4        10     9           2   
top        e         x           y         n     n           t   
freq    4208      3656        3244      2284  3528        4608   

       stalk_color_above_ring stalk_color_below_ring ring_number ring_type  \
count                    8124                   8124        8124      8124   
unique                      9                      9           3         5   
top                         w                      w           o         p   
freq                     4464                   4384        7488      3968   

       population habitat  
count        8124    8124  
unique          6       7  
top             v       d  
freq         4040    3148

In [16]:
#x:input
x=data.loc[:,"cap_shape":]
print(x)
#y:output
y=data.loc[:,["type"]] 
print(y)

     cap_shape cap_surface cap_color odor stalk_shape stalk_color_above_ring  \
0            x           s         n    p           e                      w   
1            x           s         y    a           e                      w   
2            b           s         w    l           e                      w   
3            x           y         w    p           e                      w   
4            x           s         g    n           t                      w   
...        ...         ...       ...  ...         ...                    ...   
8119         k           s         n    n           e                      o   
8120         x           s         n    n           e                      o   
8121         f           s         n    n           e                      o   
8122         k           y         n    y           t                      w   
8123         x           s         n    n           e                      o   

     stalk_color_below_ring ring_number

In [17]:
from sklearn import preprocessing
#將屬性轉為數字label
le = preprocessing.LabelEncoder()

# cap_shape: 0~5, cap_surface: 0~3 ......

# 儲存編碼後的值，之後作為input
X_encoded = []
# 儲存編碼前、後的對應值
X_dic = {}
for col_name in x:
    encoded_item = le.fit_transform(x[col_name]) # 將各col的value轉成數字
    X_encoded.append(encoded_item)

    
    # 用set排除重複值，並存入dic中
    temp_dic = {}
    key_set = sorted( set(le.inverse_transform(encoded_item)) ) # 取得原始值作為key
    value_set = set(encoded_item) # 取得編碼後的值作為val
    for i,j in zip(key_set,value_set):
        temp_dic[i] = j
    X_dic[col_name] = temp_dic

# print("x.cap_shape:\n", x.cap_shape) 
# print("X_encoded[0]:\n", X_encoded[0])
# print("X_dic[\"cap_shape\"]:\n", X_dic["cap_shape"])

#將type轉為數字label
#type: e:0 ,p:1
Y_dic = {0:"e", 1:"p"}
Y_type_label = le.fit_transform(y.type)
# print(Y_type_label)


#將屬性合併
#變成list
feature=list(zip(X_encoded[0], X_encoded[1], X_encoded[2], X_encoded[3], X_encoded[4], X_encoded[5],
                X_encoded[6], X_encoded[7], X_encoded[8], X_encoded[9], X_encoded[10]))

# for i in X_encoded:
#     print(i[0], end=" ")
# print("\n" + str(feature[0]))

#轉成array
import numpy as np
features=np.asarray(feature)
# print(feature)

In [18]:
#Import Gaussian Naive Bayes 模型 (高斯樸素貝氏)
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

# 訓練集訓練模型
# model.fit(x, y)
model.fit(features, Y_type_label)


GaussianNB(priors=None, var_smoothing=1e-09)

In [19]:
expected = Y_type_label # 代表真正的答案
predicted = model.predict(features) # 代表預測的答案
print(expected, type(expected))
print(predicted, type(predicted))
from sklearn import metrics
print(metrics.classification_report(expected, predicted)) # 把真正的答案和預測的答案拿去做統計報告
print(metrics.confusion_matrix(expected, predicted))

[1 0 0 ... 0 1 0] <class 'numpy.ndarray'>
[0 0 0 ... 0 1 0] <class 'numpy.ndarray'>
              precision    recall  f1-score   support

           0       0.87      0.78      0.82      4208
           1       0.79      0.87      0.83      3916

    accuracy                           0.83      8124
   macro avg       0.83      0.83      0.83      8124
weighted avg       0.83      0.83      0.83      8124

[[3296  912]
 [ 493 3423]]


In [20]:
input_data = [X_dic["cap_shape"]["b"], X_dic["cap_surface"]["f"], X_dic["cap_color"]["n"], X_dic["odor"]["a"],
              X_dic["stalk_shape"]["e"], X_dic["stalk_color_above_ring"]["n"], X_dic["stalk_color_below_ring"]["n"],
              X_dic["ring_number"]["n"], X_dic["ring_type"]["e"], X_dic["population"]["a"], X_dic["habitat"]["g"]]
# input_data = np.asarray(input_data)
predicted= model.predict([input_data]) # input不用轉成numpy array?
print ("Predicted Value:", predicted)
print ("Predicted Value:", Y_dic[predicted[0]])

Predicted Value: [0]
Predicted Value: e


In [23]:
# For (c)小題
print(X_dic["stalk_color_above_ring"])
print(len(X_dic["stalk_color_above_ring"]))

{'b': 0, 'c': 1, 'e': 2, 'g': 3, 'n': 4, 'o': 5, 'p': 6, 'w': 7, 'y': 8}
9


In [25]:
expected = Y_type_label # 代表真正的答案
predicted = model.predict(features) # 代表預測的答案
# For (e)(d)
print(metrics.classification_report(expected, predicted)) # 把真正的答案和預測的答案拿去做統計報告
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       0.87      0.78      0.82      4208
           1       0.79      0.87      0.83      3916

    accuracy                           0.83      8124
   macro avg       0.83      0.83      0.83      8124
weighted avg       0.83      0.83      0.83      8124

[[3296  912]
 [ 493 3423]]
